---
- name: Configure SSH
  tags: ssh
  become: true
  block:
    - name: Install
      apt:
        name: ssh
        update_cache: true

    - name: Disable password-based login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PasswordAuthentication
        line: PasswordAuthentication no
        validate: /usr/sbin/sshd -t -f %s
      notify: Restart sshd

    - name: Enable/disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^( *)?PermitRootLogin
        line: PermitRootLogin {{ (ssh_permit_root_login == true) | ternary('yes', 'no') }}
        validate: /usr/sbin/sshd -t -f %s
      notify: Restart sshd

    - name: Add authorised SSH keys
      authorized_key:
        user: "{{ item.user }}"
        key: "{{ item.key }}"
        exclusive: true  # Only allow keys specified here
      with_items: "{{ ssh_authorized_keys }}"
